# 音频文件目录
audio_cache_path:
# srt 文件目录
srt_path:
# ffmpeg 安装路径
ffmpeg:

translate_tools:
  #- baidu
  - google
  #- tencent

generate_tools:
  - aliyun
  #- google

baidu:
  app_id: xxxxxxxxxxxxxxxxx
  secret_key: xxxxxxxxxxxxxxxxxxxx
  interval: 100 #访问间隔

google:
  interval: 1000 #访问间隔
  credentials_file: ./google.json
  bucket_name: xxxxx


tencent:
  qtv: xxx
  qtk: xxxx
  interval: 1000  #访问间隔

aliyun:
  access_key_id: xxxxxxxxxxxxxxxxxxxxxxxx
  accessKey_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  app_key: xxxxxxxxxxxxxxxx
  oss_endpoint: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  bucket_name: xxxxxxxxxxxxxxxx
  bucket_domain: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  interval: 1000

# 句子结果中的单词 : 词结果中的单词
well_known_word:
  "b": "bytes"

# 词结果中的单词 : 句子结果中的单词
well_known_number:
    "zero":      0
    "one":       1
    "two":       2
    "three":     3
    "four":      4
    "five":      5
    "six":       6
    "seven":     7
    "eight":     8
    "nine":      9
    "ten":       10
    "eleven":    11
    "twelve":    12
    "thirteen":  13
    "fourteen":  14
    "fifteen":   15
    "sixteen":   16
    "seventeen": 17
    "eighteen":  18
    "nineteen":  19
    "twenty":    20
    "thirty":    30
    "forty":     40
    "fifty":     50
    "sixty":     60
    "seventy":   70
    "eighty":    80
    "ninety":    90
    "thousand":  1000
    "hundred":   100
    "million":   1000000
    "minus":     -0

